# Generated by Django 5.0.1 on 2024-02-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_attendence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clss',
            name='sub',
            field=models.CharField(default='dsp', max_length=10),
            preserve_default=False,
        ),
    ]
