# Generated by Django 5.0.1 on 2024-02-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_attendence', '0002_clss_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clss',
            name='sclass',
        ),
        migrations.RemoveField(
            model_name='clss',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='clss',
            name='tid',
        ),
    ]
