# Generated by Django 5.0.1 on 2024-02-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_attendence', '0006_alter_att_sub_attended_alter_att_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dep',
            field=models.CharField(default='CSE', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default='E2', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tname',
            field=models.CharField(max_length=20),
        ),
    ]
