# Generated by Django 5.0.1 on 2024-02-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_attendence', '0009_tsa_remove_regi_period_remove_regi_roll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsa',
            name='sclass',
            field=models.CharField(default='E2CSE4', max_length=10),
            preserve_default=False,
        ),
    ]
