# Generated by Django 5.0.1 on 2024-02-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_attendence', '0013_alter_tsa_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsa',
            name='period',
            field=models.IntegerField(),
        ),
    ]
