# Generated by Django 5.0.1 on 2024-02-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_attendence', '0014_alter_tsa_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='regi',
            name='per',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
