# Generated by Django 5.0.1 on 2024-02-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_attendence', '0015_regi_per'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regi',
            old_name='per',
            new_name='period',
        ),
    ]
