# Generated by Django 5.0.1 on 2024-02-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_attendence', '0004_clss_sclass_clss_sub_clss_tid'),
    ]

    operations = [
        migrations.CreateModel(
            name='att',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=10)),
                ('sclass', models.CharField(max_length=10)),
                ('sub', models.CharField(max_length=10)),
                ('sub_total', models.CharField(max_length=10)),
                ('sub_attended', models.CharField(max_length=10)),
            ],
        ),
    ]
