# Generated by Django 5.0.1 on 2024-02-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_attendence', '0007_student_dep_student_year_alter_student_sname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='regi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('sid', models.CharField(max_length=10)),
                ('sclass', models.CharField(max_length=10)),
                ('sub', models.CharField(max_length=10)),
                ('tm', models.DateTimeField()),
                ('period', models.IntegerField()),
            ],
        ),
    ]
