# Generated by Django 5.0.1 on 2024-02-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_attendence', '0008_regi'),
    ]

    operations = [
        migrations.CreateModel(
            name='tsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=10)),
                ('sub', models.CharField(max_length=10)),
                ('tm', models.DateTimeField()),
                ('period', models.IntegerField(max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='regi',
            name='period',
        ),
        migrations.RemoveField(
            model_name='regi',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='regi',
            name='sclass',
        ),
    ]
