# Generated by Django 5.0.1 on 2024-02-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_attendence', '0010_tsa_sclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsa',
            name='sclass',
        ),
        migrations.AlterField(
            model_name='regi',
            name='tm',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tsa',
            name='period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tsa',
            name='tm',
            field=models.DateField(),
        ),
    ]
