# Generated by Django 5.0.1 on 2024-02-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_attendence', '0011_remove_tsa_sclass_alter_regi_tm_alter_tsa_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsa',
            name='sclass',
            field=models.CharField(default='E2CSE4', max_length=10),
            preserve_default=False,
        ),
    ]
