# Generated by Django 5.0.1 on 2024-02-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_attendence', '0016_rename_per_regi_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=30),
        ),
    ]
